#!/bin/bash

yum -y install pcre pcre-devel openssl openssl-devel

cd `dirname $0`
SCRIPT_DIR=`pwd`
cd $SCRIPT_DIR

tar -xzf nginx-1.8.0.tar.gz

tar -xzf ngx_cache_purge-2.3.tar.gz

cd nginx-1.8.0

./configure --prefix=/usr/local/nginx --with-http_ssl_module --with-http_stub_status_module --with-http_gzip_static_module --add-module=../ngx_cache_purge-2.3 > /dev/null

make && make install

mkdir /usr/local/nginx/conf/vhosts

echo "/usr/local/nginx/sbin/nginx" >> /etc/rc.local


